/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.springframework.boot.spring.boot.starter.webflux)
    api(libs.org.springframework.boot.spring.boot.starter.validation)
    api(libs.org.springframework.boot.spring.boot.starter.actuator)
    api(libs.io.micrometer.micrometer.registry.prometheus)
    api(libs.io.micrometer.micrometer.tracing.bridge.otel)
    api(libs.io.opentelemetry.opentelemetry.exporter.otlp)
    api(libs.org.springframework.cloud.spring.cloud.starter.circuitbreaker.reactor.resilience4j)
    api(libs.org.springframework.boot.spring.boot.starter.data.r2dbc)
    api(libs.org.postgresql.r2dbc.postgresql)
    api(libs.org.springframework.boot.spring.boot.starter.jdbc)
    api(libs.org.flywaydb.flyway.core)
    api(libs.net.logstash.logback.logstash.logback.encoder)
    runtimeOnly(libs.org.postgresql.postgresql)
    testImplementation(libs.org.springframework.boot.spring.boot.starter.test)
    testImplementation(libs.io.projectreactor.reactor.test)
    testImplementation(libs.org.testcontainers.junit.jupiter)
    testImplementation(libs.org.testcontainers.postgresql)
}

group = "com.ngocnq2"
version = "0.0.1-SNAPSHOT"
description = "high-throughput-architect"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
